### ISSUE TITLE
Standard `free()` does not have const argument

### ISSUE THREAD

**Issue by alexreinking** [koka-lang/libhandler#7]
The typedef for [`lh_freefun`](https://github.com/koka-lang/libhandler/blob/14bd81ef1b5d39c68c71b92d769d8fb5fb2a430c/inc/libhandler.h#L337) currently has an argument type of `const void *`, which is non-conforming with the C standard library. Per the [C11 standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf), section 7.22.3.3, `free` is defined to have the following signature:

    void free(void *ptr);

Can this typedef be updated in libhandler? It currently generates warning [`C4028`](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4028) in MSVC when trying to pass the standard `free` function.

**Comment by daanx** [comment]
Fixed by f70c600 :-)

**Comment by alexreinking** [comment]
Awesome, @daanx ! Thanks!
