### ISSUE TITLE
compilation error on mac os

### ISSUE THREAD

**Issue by shazqadeer** [koka-lang/libhandler#8]
I am getting the following error when compiling on Mac OS.

build variant: debug, configuration: gcc-amd64-apple-darwin18.2.0
src/exception.c:11:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [depend] Error 1
make[2]: *** [Prt/CMakeFiles/libhandler] Error 2
make[1]: *** [Prt/CMakeFiles/libhandler.dir/all] Error 2
make: *** [all] Error 2

System Version:	macOS 10.14.1 (18B75)
Kernel Version:	Darwin 18.2.0

I think the problem is that on my computer malloc.h is in the malloc folder.  If I change that offending line to 

#include <malloc/malloc.h>

the error goes away.

**Comment by shazqadeer** [comment]
Another option is to use stdlib.h.  It looks like malloc.h is not standard on Mac OS.

https://stackoverflow.com/questions/44683812/how-do-install-c-header-files-in-mac-osx-sierra

**Comment by daanx** [comment]
Right, it seems including `malloc.h` was wrong in the first place and I should have used `stdlib.h` anyways,
see <https://stackoverflow.com/questions/12973311/difference-between-stdlib-h-and-malloc-h>
I'll fix this right away.

**Comment by shazqadeer** [comment]
@daanx : Did you get a chance to push a fix? Looks like we know what to do and the fix is simple.

**Comment by daanx** [comment]
Ah,I thought I had fixed this long ago but apperently not! Apologies. 
Fixed now,  commit 2cb30098

**Comment by daanx** [comment]
Hi Shaz,

Ha, I thought I did this a long time ago. Fixed now I hope (in the master and dev branch)

Best
  Daan

________________________________
